/* CRIE CINCO OBJETOS NESSE FORMATO
 {
NONE: ""
IDADE: ""
SEXO: ""
PROFISSÃO: ""
NACIONALIDADE: ""
 }
AO RODAR O PROGRAMA, DEVE IMPRIMIR SE A PESSOA É APROVADA OU NÃO NO PROCESSO
PARA SER APROVADA, A PESSOA DEVE SER EMANCIPADA LEGALMENTE E BRASILEIRA */
