/* FAÇA UM PROGRAMA QUE GERE UM NÚMERO ALEATÓRIO ENTRE 1 E 10, ESSE É O NÚMERO 'GANHADOR'
ENTÃO ELE TAMBÉM IRÁ GERAR UM NÚMERO ALEATÓRIO ENTRE 1 E 10, E VERIFICA SE A PESSOA GANHOU OU NÃO
EM CASO DE TER GANHADO, MOSTRA O PRÊMIO; SE NÃO GANHOU, MOSTRA OUTRA MENSAGEM */